--- #  Basic Provisioning of an AMI from our Instance
- hosts: localhost
  connection: local
  remote_user: vagrant
  become: yes
  gather_facts: no
  vars_files:
   - files/awscreds.yml
  tasks:
    - name: Basic Provisioning of an AMI from our Instance
      ec2_ami:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        instance_id: i-1dce8f93
        wait: no
        name: mynewami
        tags:
          Name: MyNewAMI
          service: TestAMIService
      register: instance
