--- # EC2 REMOTE FACTS MODULES EXAMPLE
- hosts: localhost
  connection: local
  remote_user: vagrant
  become: yes
  gather_facts: no
  vars_files:
   - files/awscreds.yml
  tasks:
    - name: Fetch the AWS Account Facts Module
      ec2_remote_facts:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
      register: remote_facts
    -  debug: msg={{ remote_facts }}
