--- #EC2 Instance Snapshot
- hosts: localhost
  connection: local
  remote_user: vagrant
  become: yes
  gather_facts: no
  vars_files:
   - files/awscreds.yml
  tasks:
   -  name: Manage the snapshot of the an instance
      ec2_snapshot:
       aws_access_key: "{{ aws_id }}"
       aws_secret_key: "{{ aws_key }}"
       region: "{{ aws_region }}"
       instance_id: i-1eb4f490
       device_name: /dev/xvda
       description: Ansible Playbook
       wait: no
