--- # EC2 METRIC ALARM EXAMPLE
- hosts: localhost
  connection: local
  remote_user: vagrant
  become: yes
  gather_facts: no
  vars_files:
   - files/awscreds.yml
  tasks:
    - name: Create secuirty group
      ec2_metric_alarm:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        state: present
        name: OurFirstAlarmTest
        metric: "CPUUtilization"
        namespace: "AWS/EC2"
        statistic: Average
        comparison: ">="
        threshold: 25.0
        period: 300
        evaluation_periods: 6
        unit: "Percent"
        description: "This alarm fires When CPU is greater then 25% for 30 mintues"
        dimensions: {'InstanceID':'i-1eb4f490'}
