--- # Find AMI Images 
- hosts: localhost
  connection: local
  remote_user: vagrant
  become: yes
  gather_facts: no
  vars_files:
   - files/awscreds.yml
  tasks:
    - name: Find AMI Images
      ec2_ami_find:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        owner: self
        ami_tags:
           Name: MyNewAMI
        no_result_action: fail
      register: ami_find
    - debug: msg={{ ami_find.results[0].ami_id }}
    - debug: msg={{ ami_find.results[0].name  }}
