--- # EC2 MODULE FOR PROVISIONING
- hosts: localhost
  connection: local
  remote_user: vagrant
  become: yes
  gather_facts: no
  vars_files:
   - files/awscreds.yml
  tasks:
    - name: Basic Provisioning of two t2.micro EC2 Instances
      ec2:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        image: ami-0103cd62
        instance_type: t2.micro
        count: 1
