--- #EC2 Instance Start/Stop/Terminate
- hosts: localhost
  connection: local
  remote_user: vagrant
  become: yes
  gather_facts: no
  vars_files:
   - files/awscreds.yml
  tasks:
   -  name: Manage the state of the an instance
      ec2:
       aws_access_key: "{{ aws_id }}"
       aws_secret_key: "{{ aws_key }}"
       region: "{{ aws_region }}"
       instance_ids: i-79b4f5f7
       state: running
